"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.clamp = exports.isHHMM = exports.isStrongPassword = exports.isEmail = void 0;
const isEmail = (s) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
exports.isEmail = isEmail;
const isStrongPassword = (s) => s.length >= 8 && /[A-Z]/.test(s) && /\d/.test(s);
exports.isStrongPassword = isStrongPassword;
const isHHMM = (s) => /^\d{2}:\d{2}$/.test(s);
exports.isHHMM = isHHMM;
const clamp = (n, lo, hi) => Math.max(lo, Math.min(hi, n));
exports.clamp = clamp;
