import type { FastifyInstance } from 'fastify';
import { registerHealth } from './health';
import { registerAuthLogin } from './auth-login';
import { registerAuthSignup } from './auth-signup';
import { registerAuthRefresh } from './auth-refresh';
import { registerAuthLogout } from './auth-logout';
import { registerMe } from './me';
import { registerPreferences } from './preferences';
import { registerMedications } from './medications';
import { registerMedicationsId } from './medications-id';
import { registerMedicationsIdActivate } from './medications-id-activate';
import { registerMedicationsIdArchive } from './medications-id-archive';
import { registerSchedules } from './schedules';
import { registerSchedulesId } from './schedules-id';
import { registerSchedulesConflicts } from './schedules-conflicts';
import { registerSchedulesResolve } from './schedules-resolve';
import { registerEscalation } from './escalation';
import { registerDoses } from './doses';
import { registerDosesId } from './doses-id';
import { registerDosesIdTake } from './doses-id-take';
import { registerDosesIdSkip } from './doses-id-skip';
import { registerDosesIdSnooze } from './doses-id-snooze';
import { registerDosesToday } from './doses-today';
import { registerDosesUpcoming } from './doses-upcoming';
import { registerDosesHistory } from './doses-history';
import { registerStreaks } from './streaks';
import { registerStreaksId } from './streaks-id';
import { registerRefills } from './refills';
import { registerRefillsId } from './refills-id';
import { registerRefillsNeeded } from './refills-needed';
import { registerCaregivers } from './caregivers';
import { registerCaregiversId } from './caregivers-id';
import { registerCaregiversIdRotate } from './caregivers-id-rotate';
import { registerCaregiversIdDigest } from './caregivers-id-digest';
import { registerSharedView } from './shared-view';
import { registerReportsAdherence } from './reports-adherence';
import { registerReportsWeekly } from './reports-weekly';
import { registerReportsMonthly } from './reports-monthly';
import { registerReportsExportCsv } from './reports-export-csv';
import { registerReportsExportPdf } from './reports-export-pdf';
import { registerReportsExportJson } from './reports-export-json';
import { registerReportsExportIcs } from './reports-export-ics';
import { registerInteractionsCheck } from './interactions-check';
import { registerInteractionsForUser } from './interactions-for-user';
import { registerInteractionsGraph } from './interactions-graph';
import { registerDrugsSearch } from './drugs-search';
import { registerDrugsId } from './drugs-id';
import { registerDrugsClasses } from './drugs-classes';
import { registerNotifications } from './notifications';
import { registerNotificationsId } from './notifications-id';
import { registerNotificationsMarkRead } from './notifications-mark-read';
import { registerNotificationsTest } from './notifications-test';
import { registerRemindersEngineRun } from './reminders-engine-run';
import { registerRemindersPending } from './reminders-pending';
import { registerWebhooksPharmacy } from './webhooks-pharmacy';
import { registerTitration } from './titration';
import { registerPillsIdentify } from './pills-identify';
import { registerRiskAdherence } from './risk-adherence';
import { registerAdminStats } from './admin-stats';
import { registerAdminUsers } from './admin-users';

export async function registerRoutes(app: FastifyInstance) {
  await registerHealth(app);
  await registerAuthLogin(app);
  await registerAuthSignup(app);
  await registerAuthRefresh(app);
  await registerAuthLogout(app);
  await registerMe(app);
  await registerPreferences(app);
  await registerMedications(app);
  await registerMedicationsId(app);
  await registerMedicationsIdActivate(app);
  await registerMedicationsIdArchive(app);
  await registerSchedules(app);
  await registerSchedulesId(app);
  await registerSchedulesConflicts(app);
  await registerSchedulesResolve(app);
  await registerEscalation(app);
  await registerDoses(app);
  await registerDosesId(app);
  await registerDosesIdTake(app);
  await registerDosesIdSkip(app);
  await registerDosesIdSnooze(app);
  await registerDosesToday(app);
  await registerDosesUpcoming(app);
  await registerDosesHistory(app);
  await registerStreaks(app);
  await registerStreaksId(app);
  await registerRefills(app);
  await registerRefillsId(app);
  await registerRefillsNeeded(app);
  await registerCaregivers(app);
  await registerCaregiversId(app);
  await registerCaregiversIdRotate(app);
  await registerCaregiversIdDigest(app);
  await registerSharedView(app);
  await registerReportsAdherence(app);
  await registerReportsWeekly(app);
  await registerReportsMonthly(app);
  await registerReportsExportCsv(app);
  await registerReportsExportPdf(app);
  await registerReportsExportJson(app);
  await registerReportsExportIcs(app);
  await registerInteractionsCheck(app);
  await registerInteractionsForUser(app);
  await registerInteractionsGraph(app);
  await registerDrugsSearch(app);
  await registerDrugsId(app);
  await registerDrugsClasses(app);
  await registerNotifications(app);
  await registerNotificationsId(app);
  await registerNotificationsMarkRead(app);
  await registerNotificationsTest(app);
  await registerRemindersEngineRun(app);
  await registerRemindersPending(app);
  await registerWebhooksPharmacy(app);
  await registerTitration(app);
  await registerPillsIdentify(app);
  await registerRiskAdherence(app);
  await registerAdminStats(app);
  await registerAdminUsers(app);
}
